"""verl agent loop for HV-TextArena episodes.

One ``run()`` is one episode: the opening chat is tokenised once, each assistant turn is
generated by the rollout server and appended as policy tokens (mask 1), each environment
reply is tokenised as a user turn and appended as context tokens (mask 0). The episode's
reward goes out as ``reward_score``, so verl's reward manager never runs; the episode
record goes out as ``reward_extra_info`` and becomes per-sample ``hvta_*`` columns for the
trainer's metrics and early stop (``hvta.rl.metrics.record_to_columns``).

The system prompt comes from the dataset row's ``raw_prompt`` when present, so a trainer
that rewrites the sampling prompt (an intervention arm) is honoured; the opening user
turn is regenerated from the task seed, which is deterministic.

``HVTALoopCore`` holds the logic with the tokenizer and generator injected, so it can be
tested without verl. ``HVTAAgentLoop`` is the thin ``AgentLoopBase`` adapter registered as
``hvta``; it is only defined when verl is importable.

Config expectations (see integrations/rl-rewardhacking/):
- ``actor_rollout_ref.rollout.mode: async``, ``multi_turn.enable: true``,
  ``data.return_raw_chat: true``
- ``rollout.response_length`` is the token budget for the whole episode (policy and
  environment tokens together); ``multi_turn.max_assistant_turns`` caps turns
- ``data.apply_chat_template_kwargs`` (e.g. ``enable_thinking: false``) is applied to every
  turn, not only the first
- the agent-loop yaml passes ``max_tokens_per_turn``; the rollout server must honour a
  ``max_tokens`` entry in sampling params (patch ``vllm_async_server.py``)
"""

import asyncio
import json
import os
import uuid
from dataclasses import dataclass, field
from typing import Any, Awaitable, Callable, Optional

from .episode import HVTAEpisode, WrapperPool
from .metrics import RECORD_COLUMNS, EpisodeRecord, aggregate_columns, record_to_columns
from .tasks import TaskSpec

__all__ = [
    "DEFAULT_MAX_TOKENS_PER_TURN",
    "RECORD_COLUMNS",
    "HVTALoopCore",
    "LoopResult",
    "aggregate_columns",
    "record_to_columns",
    "system_prompt_from_row",
    "task_from_row",
]

DEFAULT_MAX_TOKENS_PER_TURN = 256


def task_from_row(extra_info: Any) -> TaskSpec:
    """The TaskSpec a dataset row carries in ``extra_info.task`` (dict or JSON string)."""
    if isinstance(extra_info, str):
        extra_info = json.loads(extra_info)
    task = extra_info["task"]
    if isinstance(task, str):
        task = json.loads(task)
    return TaskSpec.from_dict(task)


def system_prompt_from_row(raw_prompt: Any) -> Optional[str]:
    """The system message of the row's chat, if it has one."""
    if raw_prompt is None or len(raw_prompt) == 0:
        return None
    first = raw_prompt[0]
    if isinstance(first, dict) and first.get("role") == "system":
        return first.get("content")
    return None


GenerateFn = Callable[[list[int], int], Awaitable[list[int]]]


@dataclass
class LoopResult:
    prompt_ids: list[int]
    response_ids: list[int]
    response_mask: list[int]
    reward: float
    num_turns: int
    record: EpisodeRecord
    budget_truncated: bool
    columns: dict[str, Any] = field(default_factory=dict)


class HVTALoopCore:
    """Episode-to-token-sequence logic, independent of verl."""

    def __init__(
        self,
        tokenizer: Any,
        response_length: int,
        max_assistant_turns: Optional[int] = None,
        max_tokens_per_turn: int = DEFAULT_MAX_TOKENS_PER_TURN,
        apply_chat_template_kwargs: Optional[dict] = None,
        pool: Optional[WrapperPool] = None,
        system_prompt: Optional[str] = None,
    ) -> None:
        self.tokenizer = tokenizer
        self.response_length = response_length
        self.max_assistant_turns = max_assistant_turns
        self.max_tokens_per_turn = max_tokens_per_turn
        self.template_kwargs = dict(apply_chat_template_kwargs or {})
        self.pool = pool
        self.system_prompt = system_prompt
        # Rendering a lone user turn may prepend the template's default system block
        # (Qwen2.5 does, Qwen3 does not); its token length is what to strip. Same trick as
        # verl's ToolAgentLoop.
        self.template_prefix_len = len(
            tokenizer.apply_chat_template([{}], add_generation_prompt=False, tokenize=True, **self.template_kwargs)
        )

    def _tokenize_opening(self, messages: list[dict]) -> list[int]:
        return list(
            self.tokenizer.apply_chat_template(messages, add_generation_prompt=True, tokenize=True, **self.template_kwargs)
        )

    def _tokenize_user_turn(self, content: str) -> list[int]:
        ids = self.tokenizer.apply_chat_template(
            [{"role": "user", "content": content}], add_generation_prompt=True, tokenize=True, **self.template_kwargs
        )
        return list(ids)[self.template_prefix_len :]

    async def run(self, task: TaskSpec, generate: GenerateFn, system_prompt: Optional[str] = None) -> LoopResult:
        episode = HVTAEpisode(
            task, system_prompt=system_prompt if system_prompt is not None else self.system_prompt, pool=self.pool
        )
        opening = episode.reset()
        prompt_ids = self._tokenize_opening(opening)
        seq: list[int] = list(prompt_ids)
        mask: list[int] = []
        assistant_turns = 0
        user_turns = 1
        budget_truncated = False

        try:
            while True:
                remaining = self.response_length - len(mask)
                if remaining <= 0:
                    budget_truncated = True
                    break
                max_tokens = min(self.max_tokens_per_turn, remaining)
                gen_ids = list(await generate(seq, max_tokens))
                assistant_turns += 1
                seq += gen_ids
                mask += [1] * len(gen_ids)
                text = self.tokenizer.decode(gen_ids, skip_special_tokens=True)
                result = episode.step(text)
                if result.done:
                    break
                if len(mask) >= self.response_length:
                    budget_truncated = True
                    break
                if self.max_assistant_turns and assistant_turns >= self.max_assistant_turns:
                    budget_truncated = True
                    break
                user_ids = self._tokenize_user_turn(result.user_message)
                if len(mask) + len(user_ids) >= self.response_length:
                    budget_truncated = True
                    break
                seq += user_ids
                mask += [0] * len(user_ids)
                user_turns += 1
        finally:
            if not episode.done:
                episode.force_end("rollout budget exhausted" if budget_truncated else "agent loop error")

        record = episode.record
        record.response_tokens = sum(mask)
        response_ids = seq[len(prompt_ids) :][: self.response_length]
        mask = mask[: self.response_length]
        num_turns = assistant_turns + user_turns + 1
        reward = float(record.reward if record.reward is not None else 0.0)
        columns = record_to_columns(record, num_turns=num_turns, budget_truncated=budget_truncated)
        return LoopResult(
            prompt_ids=prompt_ids,
            response_ids=response_ids,
            response_mask=mask,
            reward=reward,
            num_turns=num_turns,
            record=record,
            budget_truncated=budget_truncated,
            columns=columns,
        )


try:  # verl is only present on the training image
    from verl.experimental.agent_loop.agent_loop import AgentLoopBase, AgentLoopMetrics, AgentLoopOutput, register
except ImportError:  # pragma: no cover
    AgentLoopBase = None  # type: ignore[assignment]

if AgentLoopBase is not None:

    @register("hvta")
    class HVTAAgentLoop(AgentLoopBase):
        """verl adapter. Extra yaml kwargs: ``max_tokens_per_turn`` (env HVTA_MAX_TOKENS_PER_TURN overrides)."""

        @classmethod
        def init_class(cls, config, tokenizer, processor, **kwargs):
            if cls._class_initialized:
                return
            cls._class_initialized = True
            rollout = config.actor_rollout_ref.rollout
            per_turn = os.environ.get("HVTA_MAX_TOKENS_PER_TURN") or kwargs.get("max_tokens_per_turn", DEFAULT_MAX_TOKENS_PER_TURN)
            cls.core = HVTALoopCore(
                tokenizer=tokenizer,
                response_length=rollout.response_length,
                max_assistant_turns=rollout.multi_turn.max_assistant_turns,
                max_tokens_per_turn=int(per_turn),
                apply_chat_template_kwargs=config.data.get("apply_chat_template_kwargs", {}),
                pool=WrapperPool(),
            )

        async def run(self, sampling_params: dict[str, Any], **kwargs) -> AgentLoopOutput:
            task = task_from_row(kwargs["extra_info"])
            system_prompt = system_prompt_from_row(kwargs.get("raw_prompt"))
            request_id = uuid.uuid4().hex
            metrics = AgentLoopMetrics()
            loop = asyncio.get_running_loop()

            async def generate(prompt_ids: list[int], max_tokens: int) -> list[int]:
                params = dict(sampling_params)
                params["max_tokens"] = max_tokens
                start = loop.time()
                out = await self.server_manager.generate(
                    request_id=request_id, prompt_ids=prompt_ids, sampling_params=params
                )
                metrics.generate_sequences += loop.time() - start
                return list(out.token_ids)

            result = await self.core.run(task, generate, system_prompt=system_prompt)
            return AgentLoopOutput(
                prompt_ids=result.prompt_ids,
                response_ids=result.response_ids,
                response_mask=result.response_mask,
                reward_score=result.reward,
                num_turns=result.num_turns,
                metrics=metrics,
                extra_fields={"reward_extra_info": result.columns},
            )
